# Generated by Django 3.2.7 on 2022-01-12 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notes1',
            fields=[
                ('notesid', models.AutoField(primary_key=True, serialize=False)),
                ('notestitle', models.CharField(max_length=60)),
                ('category', models.CharField(blank=True, choices=[('educational', 'educational'), ('Academic', 'Academic'), ('Misc', 'Misc')], max_length=50)),
                ('coursefor', models.CharField(blank=True, choices=[('BTech', 'BTech'), ('B.E', 'B.E')], max_length=50)),
                ('subject', models.CharField(blank=True, choices=[('TOC', 'TOC'), ('DBMS', 'DBMS'), ('Data structure', 'Data structure'), ('ADA', 'ADA'), ('Computer networking', 'Computer networking'), ('compiler Design', 'compiler Design')], max_length=50)),
                ('semeter', models.CharField(blank=True, max_length=30)),
                ('branch', models.CharField(blank=True, choices=[('Computer science', 'Computer science'), ('Mechanical', 'Mechanical'), ('Civil', 'civil'), ('EC', 'EC'), ('EX', 'EX')], max_length=30)),
                ('youtubevideolink', models.CharField(blank=True, max_length=300, null=True)),
                ('price', models.IntegerField()),
                ('notedesc', models.TextField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='notesfile',
            fields=[
                ('Nfileif', models.AutoField(primary_key=True, serialize=False)),
                ('file_title', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(upload_to='Study/notes')),
                ('filelink', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Study.notes1')),
            ],
        ),
    ]
