# Generated by Django 3.2.7 on 2023-07-25 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes1',
            name='branch',
            field=models.CharField(blank=True, choices=[('Computer science', 'Computer science'), ('Mechanical', 'Mechanical'), ('Civil', 'civil'), ('EC', 'EC'), ('EX', 'EX')], max_length=30, verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='notes1',
            name='category',
            field=models.CharField(blank=True, choices=[('educational', 'educational'), ('Academic', 'Academic'), ('Misc', 'Misc')], max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='notes1',
            name='coursefor',
            field=models.CharField(blank=True, choices=[('BTech', 'BTech'), ('B.E', 'B.E')], max_length=50, verbose_name='Course Stream'),
        ),
        migrations.AlterField(
            model_name='notes1',
            name='notedesc',
            field=models.TextField(blank=True, max_length=800, verbose_name='Notes Description'),
        ),
        migrations.AlterField(
            model_name='notes1',
            name='notestitle',
            field=models.CharField(max_length=60, verbose_name='Notes Title'),
        ),
        migrations.AlterField(
            model_name='notes1',
            name='price',
            field=models.IntegerField(blank=True, default=99, verbose_name='Course Price'),
        ),
        migrations.AlterField(
            model_name='notes1',
            name='semeter',
            field=models.CharField(blank=True, max_length=30, verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='notes1',
            name='subject',
            field=models.CharField(blank=True, choices=[('TOC', 'TOC'), ('DBMS', 'DBMS'), ('Data structure', 'Data structure'), ('ADA', 'ADA'), ('Computer networking', 'Computer networking'), ('compiler Design', 'compiler Design')], max_length=50, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='notes1',
            name='youtubevideolink',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Youtube Video Link'),
        ),
        migrations.AlterField(
            model_name='notesfile',
            name='file',
            field=models.FileField(upload_to='Study/notes', verbose_name='Notes File'),
        ),
        migrations.AlterField(
            model_name='notesfile',
            name='file_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='File Title'),
        ),
        migrations.AlterField(
            model_name='notesfile',
            name='filelink',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Study.notes1', verbose_name='File Link'),
        ),
    ]
