# Generated by Django 3.2.7 on 2023-07-29 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0002_auto_20230725_2313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes1',
            options={'verbose_name': 'Notes', 'verbose_name_plural': 'Notes'},
        ),
        migrations.AlterModelOptions(
            name='notesfile',
            options={'verbose_name': 'Notes File', 'verbose_name_plural': 'Notes File'},
        ),
    ]
