# Generated by Django 3.2.7 on 2023-07-29 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0003_auto_20230729_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='branchForNotes',
            fields=[
                ('branchId', models.AutoField(primary_key=True, serialize=False)),
                ('branchName', models.CharField(max_length=35, verbose_name='branch Name')),
            ],
        ),
        migrations.CreateModel(
            name='categoryOfNotes',
            fields=[
                ('CategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=35, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='CourseFor',
            fields=[
                ('CourseId', models.AutoField(primary_key=True, serialize=False)),
                ('CourseName', models.CharField(max_length=35, verbose_name='Course Name')),
            ],
        ),
        migrations.CreateModel(
            name='semeserForNotes',
            fields=[
                ('semesterId', models.AutoField(primary_key=True, serialize=False)),
                ('semesterName', models.CharField(max_length=35, verbose_name='semester Name')),
            ],
        ),
        migrations.CreateModel(
            name='subjectOfNotes',
            fields=[
                ('subjectId', models.AutoField(primary_key=True, serialize=False)),
                ('subjectName', models.CharField(max_length=35, verbose_name='subject Name')),
            ],
        ),
        migrations.AlterField(
            model_name='notes1',
            name='branch',
            field=models.OneToOneField(blank=True, max_length=30, on_delete=django.db.models.deletion.CASCADE, to='Study.semeserfornotes', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='notes1',
            name='category',
            field=models.OneToOneField(blank=True, max_length=50, on_delete=django.db.models.deletion.CASCADE, to='Study.categoryofnotes', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='notes1',
            name='coursefor',
            field=models.OneToOneField(blank=True, max_length=50, on_delete=django.db.models.deletion.CASCADE, to='Study.coursefor', verbose_name='Course Stream'),
        ),
        migrations.AlterField(
            model_name='notes1',
            name='semeter',
            field=models.OneToOneField(blank=True, max_length=30, on_delete=django.db.models.deletion.CASCADE, to='Study.branchfornotes', verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='notes1',
            name='subject',
            field=models.OneToOneField(blank=True, max_length=50, on_delete=django.db.models.deletion.CASCADE, to='Study.subjectofnotes', verbose_name='Subject'),
        ),
    ]
