# Generated by Django 3.2.7 on 2023-09-22 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0005_auto_20230730_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchfornotes',
            options={'verbose_name': 'Semester', 'verbose_name_plural': 'Semester'},
        ),
        migrations.AlterModelOptions(
            name='semeserfornotes',
            options={'verbose_name': 'Branch', 'verbose_name_plural': 'Branch'},
        ),
    ]
