# Generated by Django 3.2.7 on 2022-07-28 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearnMODEL',
            fields=[
                ('LearnModelid', models.AutoField(primary_key=True, serialize=False)),
                ('LearnTitle', models.CharField(max_length=60, unique=True)),
                ('SubLearnHeading', models.CharField(blank=True, max_length=50)),
                ('Videofile', models.FileField(upload_to='LearnWithUS/videos')),
                ('youtubevideolink', models.CharField(blank=True, max_length=300, null=True)),
                ('notedesc', models.TextField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='notesfile',
            fields=[
                ('Nfileif', models.AutoField(primary_key=True, serialize=False)),
                ('file_title', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(upload_to='LearnWithUS/videos')),
                ('filelink', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LearnWithUS.learnmodel')),
            ],
        ),
    ]
