# Generated by Django 3.2.7 on 2023-07-25 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearnWithUS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnmodel',
            name='LearnTitle',
            field=models.CharField(max_length=60, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='learnmodel',
            name='SubLearnHeading',
            field=models.CharField(blank=True, max_length=50, verbose_name='Sub-Heading '),
        ),
        migrations.AlterField(
            model_name='learnmodel',
            name='Videofile',
            field=models.FileField(blank=True, upload_to='LearnWithUS/videos', verbose_name='Video File'),
        ),
        migrations.AlterField(
            model_name='learnmodel',
            name='notedesc',
            field=models.TextField(blank=True, max_length=800, verbose_name='Notes Description'),
        ),
        migrations.AlterField(
            model_name='learnmodel',
            name='youtubevideolink',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Youtube Video Link'),
        ),
        migrations.AlterField(
            model_name='notesfile',
            name='file',
            field=models.FileField(upload_to='LearnWithUS/videos', verbose_name='Upload File'),
        ),
        migrations.AlterField(
            model_name='notesfile',
            name='file_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='File Title'),
        ),
        migrations.AlterField(
            model_name='notesfile',
            name='filelink',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LearnWithUS.learnmodel', verbose_name='File Link'),
        ),
    ]
