# Generated by Django 3.2.7 on 2023-07-25 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Projects1', '0007_auto_20230725_2313'),
        ('Home', '0004_student_b_mobno'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsEnrolled',
            fields=[
                ('CEid', models.AutoField(primary_key=True, serialize=False)),
                ('courseid', models.ManyToManyField(blank=True, to='Projects1.Projects1', verbose_name='Courses Enrolled ID')),
                ('profileId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Courseenrolled',
        ),
    ]
