# Generated by Django 3.2.7 on 2021-12-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects1',
            name='category',
            field=models.CharField(choices=[('Web development', 'Web development'), ('Machine Learning', 'Machine Learning'), ('Data Science', 'Data Science'), ('PHP', 'PHP'), ('C/C++', 'C/C++'), ('Others', 'Others')], max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='projects1',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
