# Generated by Django 3.2.7 on 2021-12-29 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects1', '0003_pelcon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('Contentid', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=50)),
                ('fileup', models.FileField(upload_to='Projects1/filesup/')),
                ('coverup', models.ImageField(upload_to='Projects1/covers/')),
                ('projasso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Projects1.projects1')),
            ],
        ),
    ]
