# Generated by Django 3.2.7 on 2022-01-08 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects1', '0005_courseenrolled_sociallinks_student_b'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallinks',
            name='profileId',
        ),
        migrations.RemoveField(
            model_name='student_b',
            name='User',
        ),
        migrations.DeleteModel(
            name='Courseenrolled',
        ),
        migrations.DeleteModel(
            name='SocialLinks',
        ),
        migrations.DeleteModel(
            name='Student_B',
        ),
    ]
