# Generated by Django 3.2.7 on 2023-07-25 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Projects1', '0006_auto_20220109_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='coverup',
            field=models.ImageField(upload_to='Projects1/covers/', verbose_name='Cover page for File'),
        ),
        migrations.AlterField(
            model_name='content',
            name='filename',
            field=models.CharField(max_length=50, verbose_name='File Name'),
        ),
        migrations.AlterField(
            model_name='content',
            name='fileup',
            field=models.FileField(upload_to='Projects1/filesup/', verbose_name='File Upload'),
        ),
        migrations.AlterField(
            model_name='projects1',
            name='Availability',
            field=models.BooleanField(blank=True, verbose_name='Availability of Project'),
        ),
        migrations.AlterField(
            model_name='projects1',
            name='Image',
            field=models.ImageField(blank=True, upload_to='Projects1/images', verbose_name='Image for Project'),
        ),
        migrations.AlterField(
            model_name='projects1',
            name='category',
            field=models.CharField(blank=True, choices=[('Web development', 'Web development'), ('Machine Learning', 'Machine Learning'), ('Data Science', 'Data Science'), ('PHP', 'PHP'), ('C/C++', 'C/C++'), ('Others', 'Others')], max_length=35, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='projects1',
            name='creator',
            field=models.CharField(blank=True, max_length=50, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='projects1',
            name='datecreated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='projects1',
            name='desc',
            field=models.CharField(blank=True, max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='projects1',
            name='introvideo',
            field=models.FileField(blank=True, upload_to='Projects1/videos', verbose_name='Video for Project'),
        ),
        migrations.AlterField(
            model_name='projects1',
            name='projectname',
            field=models.CharField(max_length=100, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='projects1',
            name='purpose',
            field=models.CharField(blank=True, max_length=250, verbose_name='Purpose of Project'),
        ),
        migrations.AlterField(
            model_name='projects1',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=4, verbose_name='Rating'),
        ),
    ]
