# Generated by Django 3.2.7 on 2023-07-29 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects1', '0007_auto_20230725_2313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'Projects Content', 'verbose_name_plural': 'Projects Content'},
        ),
        migrations.AlterModelOptions(
            name='projects1',
            options={'verbose_name': 'Site Projects', 'verbose_name_plural': 'Site Projects'},
        ),
    ]
