# Generated by Django 3.2.7 on 2023-07-29 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_remove_products_category'),
        ('Projects1', '0008_auto_20230729_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects1',
            name='category',
        ),
        migrations.AddField(
            model_name='projects1',
            name='categoryF',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.categoryfield', verbose_name='Category'),
        ),
    ]
