# Generated by Django 3.2.7 on 2023-07-30 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_alter_products_categoryf'),
        ('Projects1', '0009_auto_20230729_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects1',
            name='categoryF',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.categoryfield', verbose_name='Category'),
        ),
    ]
