# Generated by Django 3.2.7 on 2022-01-06 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('contactno', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='The format should be exactly be of 10 digits', regex='^\\+?1?\\d{10}$')])),
                ('query', models.TextField()),
            ],
        ),
    ]
