# Generated by Django 3.2.7 on 2023-07-25 17:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='coverup',
            field=models.ImageField(upload_to='Products/covers/', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='content',
            name='filename',
            field=models.CharField(max_length=50, verbose_name='File Name'),
        ),
        migrations.AlterField(
            model_name='content',
            name='fileup',
            field=models.FileField(upload_to='Products/filesup/', verbose_name='File Upload'),
        ),
        migrations.AlterField(
            model_name='content',
            name='projasso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.products', verbose_name='Project ID'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Availability',
            field=models.BooleanField(default=True, verbose_name='Is it Available ?'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Image',
            field=models.ImageField(blank=True, upload_to='Pproducts/images', verbose_name='Image for Product'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Web development', 'Web development'), ('Machine Learning', 'Machine Learning'), ('Data Science', 'Data Science'), ('PHP', 'PHP'), ('C/C++', 'C/C++'), ('Others', 'Others')], default='Machine Learning', max_length=35, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='creator',
            field=models.CharField(blank=True, max_length=50, verbose_name='Creator Name'),
        ),
        migrations.AlterField(
            model_name='products',
            name='datecreated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='products',
            name='desc',
            field=models.CharField(blank=True, max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='products',
            name='introvideo',
            field=models.FileField(blank=True, upload_to='Pproducts/videos', verbose_name='Introduction Video'),
        ),
        migrations.AlterField(
            model_name='products',
            name='productname',
            field=models.CharField(max_length=100, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='products',
            name='purpose',
            field=models.CharField(blank=True, max_length=250, verbose_name='Purpose of Product'),
        ),
        migrations.AlterField(
            model_name='products',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=4, verbose_name='Rating of Product'),
        ),
    ]
