# Generated by Django 3.2.7 on 2023-07-29 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20230729_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryField',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=35, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'Products Category Field',
                'verbose_name_plural': 'Products Category Field',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='categoryF',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.categoryfield', verbose_name='Category'),
        ),
    ]
