# Generated by Django 3.2.7 on 2023-07-29 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_auto_20230729_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
    ]
